<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <UseWindowsForms>true</UseWindowsForms>
	  <ApplicationIcon>bin\Debug\net8.0-windows\Images\Logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net8.0-windows\Images\Logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="9.0.0" />
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.0-rc6.1" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
    <PackageReference Include="System.IO.Ports" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Forms\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SQL\SQL.csproj" />
    <ProjectReference Include="..\Framework2Core\Framework2Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="HZH_Controls">
      <HintPath>bin\Debug\net8.0-windows\HZH_Controls.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
